#here it is...
use CCv4;

INSERT INTO USERS(username,email,password,first_name,last_name,description,type,snow_sports,water_sports,land_sports,air_sports) VALUES ('user1','abc1@email.net','abcd1201','Sean','Klinglesmith','cool dude who LIKES to film using drones or otherwise','photographer,filmographer,droneOperator','snowboard','surf','skateboard,BMX,mountainBiking','skydive,hangGlide');
INSERT INTO USERS(username,email,password,first_name,last_name,description,type,snow_sports,water_sports,land_sports,air_sports) VALUES ('user2','abc2@email.net','abcd1202','Christian','Marcy','rad man who loves to shred','athlete','ski','waterSki','skateboard','hangGlide');
INSERT INTO USERS(username,email,password,first_name,last_name,description,type,snow_sports,water_sports,land_sports,air_sports) VALUES ('user3','abc3@email.net','abcd1203','RJ','Boucher','pro dude who knows how to carve','athlete,proAthlete','snowboard,ski,snowmobile','surf,waterSki','BMX','skydive,hangGlide');
INSERT INTO USERS(username,email,password,first_name,last_name,description,type,snow_sports,water_sports,land_sports,air_sports) VALUES ('user4','abc4@email.net','abcd1204','Brandon','Wheeler','awesome bro who loves to shred the gnar','athlete','snowboard','surf','mountainBiking','skydive');
INSERT INTO USERS(username,email,password,first_name,last_name,description,type,snow_sports,water_sports,land_sports,air_sports) VALUES ('user5','abc5@email.net','abcd1205','Fred','Budde','fan of sports and loves to take pictures','photographer,fan','ski','waterSki',NULL,NULL);
INSERT INTO USERS(username,email,password,first_name,last_name,description,type,snow_sports,water_sports,land_sports,air_sports) VALUES ('user6','abc6@email.net','abcd1206','Md','Monir','loves to film action sequences','filmographer','snowboard,ski,snowmobile','surf,waterSki','skateboard,BMX,mountainBiking','skydive,hangGlide');
INSERT INTO USERS(username,email,password,first_name,last_name,description,type,snow_sports,water_sports,land_sports,air_sports) VALUES ('user7','abc7@email.net','abcd1207','Dhruv','Patel','cool dude who LIKES to film using drones or otherwise','photographer,filmographer,droneOperator','snowboard','surf','skateboard','hangGlide');
INSERT INTO USERS(username,email,password,first_name,last_name,description,type,snow_sports,water_sports,land_sports,air_sports) VALUES ('user8','abc8@email.net','abcd1208','Dylan','Anderson','rad man who loves to shred','athlete,proAthlete,droneOperator','ski','waterSki','BMX','skydive,hangGlide');
INSERT INTO USERS(username,email,password,first_name,last_name,description,type,snow_sports,water_sports,land_sports,air_sports) VALUES ('user9','abc9@email.net','abcd1209','Sue','Smith','fan and athlete','athlete,fan','snowboard,ski,snowmobile','surf,waterSki','mountainBiking','skydive');
INSERT INTO USERS(username,email,password,first_name,last_name,description,type,snow_sports,water_sports,land_sports,air_sports) VALUES ('user10','abc10@email.net','abcd1210','Sally','Smith','cool dude who LIKES to film using drones or otherwise','photographer,filmographer,droneOperator','snowboard','surf',NULL,NULL);
INSERT INTO USERS(username,email,password,first_name,last_name,description,type,snow_sports,water_sports,land_sports,air_sports) VALUES ('user11','abc11@email.net','abcd1211','Susan','Smith','pro dude who knows how to carve','athlete,proAthlete','ski','waterSki','skateboard,BMX,mountainBiking','skydive,hangGlide');
INSERT INTO USERS(username,email,password,first_name,last_name,description,type,snow_sports,water_sports,land_sports,air_sports) VALUES ('user12','abc12@email.net','abcd1212','Bob','Smith','fan and athlete','athlete,fan','snowboard,ski,snowmobile','surf,waterSki','skateboard','hangGlide');
INSERT INTO USERS(username,email,password,first_name,last_name,description,type,snow_sports,water_sports,land_sports,air_sports) VALUES ('user13','abc13@email.net','abcd1213','Tony','Smith','cool dude who LIKES to film using drones or otherwise','photographer,filmographer,droneOperator','snowboard','surf','BMX','skydive,hangGlide');
INSERT INTO USERS(username,email,password,first_name,last_name,description,type,snow_sports,water_sports,land_sports,air_sports) VALUES ('user14','abc14@email.net','abcd1214','Shaun','Smith','pro dude who knows how to carve','athlete,proAthlete','ski','waterSki','mountainBiking','skydive');
INSERT INTO USERS(username,email,password,first_name,last_name,description,type,snow_sports,water_sports,land_sports,air_sports) VALUES ('user15','abc15@email.net','abcd1215','Thomas','Smith','fan and athlete','athlete,fan','snowboard,ski,snowmobile','surf,waterSki',NULL,NULL);
INSERT INTO USERS(username,email,password,first_name,last_name,description,type,snow_sports,water_sports,land_sports,air_sports) VALUES ('user16','abc16@email.net','abcd1216','Tom','Smith','cool dude who LIKES to film using drones or otherwise','photographer,filmographer,droneOperator','snowboard','surf','skateboard,BMX,mountainBiking','skydive,hangGlide');
INSERT INTO USERS(username,email,password,first_name,last_name,description,type,snow_sports,water_sports,land_sports,air_sports) VALUES ('user17','abc17@email.net','abcd1217','Brittany','Smith','pro dude who knows how to carve','athlete,proAthlete','ski','waterSki','skateboard','hangGlide');
INSERT INTO USERS(username,email,password,first_name,last_name,description,type,snow_sports,water_sports,land_sports,air_sports) VALUES ('user18','abc18@email.net','abcd1218','Helen','Smith','fan and athlete','athlete,fan','snowboard,ski,snowmobile','surf,waterSki','BMX','skydive,hangGlide');
INSERT INTO USERS(username,email,password,first_name,last_name,description,type,snow_sports,water_sports,land_sports,air_sports) VALUES ('user19','abc19@email.net','abcd1219','Harold','Smith','cool dude who LIKES to film using drones or otherwise','photographer,filmographer,droneOperator','snowboard','surf','mountainBiking','skydive');
INSERT INTO USERS(username,email,password,first_name,last_name,description,type,snow_sports,water_sports,land_sports,air_sports) VALUES ('user20','abc20@email.net','abcd1220','Anthony','Smith','pro dude who knows how to carve','athlete,proAthlete','ski','waterSki',NULL,NULL);
INSERT INTO USERS(username,email,password,first_name,last_name,description,type,snow_sports,water_sports,land_sports,air_sports) VALUES ('user21','abc21@email.net','abcd1221','Alice','Smith','fan and athlete','athlete,fan','snowboard,ski,snowmobile','surf,waterSki','skateboard,BMX,mountainBiking','skydive,hangGlide');
INSERT INTO USERS(username,email,password,first_name,last_name,description,type,snow_sports,water_sports,land_sports,air_sports) VALUES ('user22','abc22@email.net','abcd1222','Mary','Smith','cool dude who LIKES to film using drones or otherwise','photographer,filmographer,droneOperator','snowboard','surf','skateboard','hangGlide');
INSERT INTO USERS(username,email,password,first_name,last_name,description,type,snow_sports,water_sports,land_sports,air_sports) VALUES ('user23','abc23@email.net','abcd1223','Mike','Smith','pro dude who knows how to carve','athlete,proAthlete','ski','waterSki','BMX','skydive,hangGlide');
INSERT INTO USERS(username,email,password,first_name,last_name,description,type,snow_sports,water_sports,land_sports,air_sports) VALUES ('user24','abc24@email.net','abcd1224','Charles','Smith','fan and athlete','athlete,fan','snowboard,ski,snowmobile','surf,waterSki','mountainBiking','skydive');
INSERT INTO USERS(username,email,password,first_name,last_name,description,type,snow_sports,water_sports,land_sports,air_sports) VALUES ('user25','abc25@email.net','abcd1225','Debbie','Smith','cool dude who LIKES to film using drones or otherwise','photographer,filmographer,droneOperator','snowboard','surf',NULL,NULL);
INSERT INTO USERS(username,email,password,first_name,last_name,description,type,snow_sports,water_sports,land_sports,air_sports) VALUES ('user26','abc26@email.net','abcd1226','Donald','Smith','pro dude who knows how to carve','athlete,proAthlete','ski','waterSki','skateboard,BMX,mountainBiking','skydive,hangGlide');
INSERT INTO USERS(username,email,password,first_name,last_name,description,type,snow_sports,water_sports,land_sports,air_sports) VALUES ('user27','abc27@email.net','abcd1227','Steven','Smith','fan and athlete','athlete,fan','snowboard,ski,snowmobile','surf,waterSki','skateboard','hangGlide');
INSERT INTO USERS(username,email,password,first_name,last_name,description,type,snow_sports,water_sports,land_sports,air_sports) VALUES ('user28','abc28@email.net','abcd1228','Ruth','Smith','cool dude who LIKES to film using drones or otherwise','photographer,filmographer,droneOperator','snowboard','surf','BMX','skydive,hangGlide');
INSERT INTO USERS(username,email,password,first_name,last_name,description,type,snow_sports,water_sports,land_sports,air_sports) VALUES ('user29','abc29@email.net','abcd1229','Ronald','Smith','pro dude who knows how to carve','athlete,proAthlete','ski','waterSki','mountainBiking','skydive');
INSERT INTO USERS(username,email,password,first_name,last_name,description,type,snow_sports,water_sports,land_sports,air_sports) VALUES ('user30','abc30@email.net','abcd1230','Xavier','Smith','fan and athlete','athlete,fan','snowboard,ski,snowmobile',NULL,NULL,NULL);
INSERT INTO USERS(username,email,password,first_name,last_name,description,type,snow_sports,water_sports,land_sports,air_sports) VALUES ('DukeSilver101','abc31@email.net','baconandeggs','Ronald','Swanson','fan and athlete','athlete,fan','ski','surf','skateboard',NULL);
INSERT INTO USERS(username,email,password,first_name,last_name,description,type,snow_sports,water_sports,land_sports,air_sports) VALUES ('Darius','abc32@email.net','dunkmaster','Darius','Noxus','dunk master flex','athlete,fan','snowboard','surf','skateboard','skydive');
INSERT INTO USERS(username,email,password,first_name,last_name,description,type,snow_sports,water_sports,land_sports,air_sports) VALUES ('Draven','abc33@email.net','axe','Draven','Noxus','welcome to the league of draven','athlete,fan','ski','surf',NULL,NULL);
INSERT INTO USERS(username,email,password,first_name,last_name,description,type,snow_sports,water_sports,land_sports,air_sports) VALUES ('Kled','abc34@email.net','myLand','Kled','Yordle','I am Kled! High Major Commodore of the First Legion','photographer','ski','surf,waterSki',NULL,'hangGlide');
INSERT INTO USERS(username,email,password,first_name,last_name,description,type,snow_sports,water_sports,land_sports,air_sports) VALUES ('MotherOfDragons22','abc35@email.net','wherearemydragons','Daenerys','Targarian','Daenerys of the House','athlete,fan','snowboard','surf',NULL,'hangGlide');
INSERT INTO USERS(username,email,password,first_name,last_name,description,type,snow_sports,water_sports,land_sports,air_sports) VALUES ('KingInTheNorth','abc36@email.net','ILoveYgritt','Jon','Snow','I know nothing','athlete','snowboard,ski,snowmobile',NULL,NULL,NULL);
INSERT INTO USERS(username,email,password,first_name,last_name,description,type,snow_sports,water_sports,land_sports,air_sports) VALUES ('ThreeEyedRaven','abc37@email.net','luvs2climb','Brandon','Stark','I''m the three eyed raven now','droneOperator','snowboard,ski,snowmobile','surf,waterSki','skateboard,BMX,mountainBiking','skydive,hangGlide');
INSERT INTO USERS(username,email,password,first_name,last_name,description,type,snow_sports,water_sports,land_sports,air_sports) VALUES ('pitterPatter22','abc38@email.com','letsgetater','Wayne','letterkenny','a snowmobile''s a sled, a sled''s a snowmobile','athlete','snowmobile',NULL,NULL,NULL);
INSERT INTO USERS(username,email,password,first_name,last_name,description,type,snow_sports,water_sports,land_sports,air_sports) VALUES ('NotMtForte11','abc39@email.com','catsarecute','Katie','letterkenny','not my forte','fan',NULL,NULL,NULL,NULL);
INSERT INTO USERS(username,email,password,first_name,last_name,description,type,snow_sports,water_sports,land_sports,air_sports) VALUES ('SquirleyDan','abc40@email.com','supersquirley','Dan','letterkenny','i dont know how tricia would feels about this ms katies','athlete','snowmobile','surf','skateboard','skydive');
INSERT INTO USERS(username,email,password,first_name,last_name,description,type,snow_sports,water_sports,land_sports,air_sports) VALUES ('EnterTheDragon40','abc41@email.com','TheDragon1940','Bruce','Lee','be water my friend','athlete,proAthlete','snowboard,ski,snowmobile','surf,waterSki','skateboard,BMX,mountainBiking','skydive,hangGlide');

INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (1,2,'normal','hello there','normal',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (1,3,'buddyRequest','be my buddy','buddyRequest',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (1,4,'attendRequest','can I attend your carve?','attendRequest',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (1,5,'invite','yo bud come carve with me','invite',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (1,6,'normal','hello there','normal',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (1,7,'invite','yo bud come carve with me','invite',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (1,8,'normal','hello there','normal',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (2,1,'reply','im getting back to you','reply',1);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (2,4,'normal','hello there','normal',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (2,5,'buddyRequest','be my buddy','buddyRequest',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (2,6,'attendRequest','can I attend your carve?','attendRequest',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (2,7,'invite','yo bud come carve with me','invite',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (2,8,'invite','yo bud come carve with me','invite',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (2,9,'normal','hello there','normal',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (2,1,'normal','hello there','normal',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (3,1,'normal','hello there','normal',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (3,1,'buddyAccept','sure ill be your bud','buddyAccept',2);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (3,2,'normal','hello there','normal',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (3,3,'normal','hello there','normal',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (3,4,'normal','hello there','normal',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (3,5,'invite','yo bud come carve with me','invite',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (3,6,'invite','yo bud come carve with me','invite',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (3,7,'buddyRequest','be my buddy','buddyRequest',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (3,1,'normal','hello there','normal',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (3,9,'normal','hello there','normal',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (3,10,'normal','hello there','normal',NULL);

INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (1,2,'normal','hello there','normal',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (1,3,'buddyRequest','be my buddy','buddyRequest',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (1,4,'attendRequest','can I attend your carve?','attendRequest',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (1,5,'invite','yo bud come carve with me','invite',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (1,6,'normal','hello there','normal',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (1,7,'invite','yo bud come carve with me','invite',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (1,8,'normal','hello there','normal',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (2,1,'reply','im getting back to you','reply',1);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (2,4,'normal','hello there','normal',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (2,5,'buddyRequest','be my buddy','buddyRequest',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (2,6,'attendRequest','can I attend your carve?','attendRequest',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (2,7,'invite','yo bud come carve with me','invite',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (2,8,'invite','yo bud come carve with me','invite',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (2,9,'normal','hello there','normal',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (2,1,'normal','hello there','normal',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (3,1,'normal','hello there','normal',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (3,1,'buddyAccept','sure ill be your bud','buddyAccept',2);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (3,2,'normal','hello there','normal',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (3,3,'normal','hello there','normal',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (3,4,'normal','hello there','normal',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (3,5,'invite','yo bud come carve with me','invite',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (3,6,'invite','yo bud come carve with me','invite',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (3,7,'buddyRequest','be my buddy','buddyRequest',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (3,1,'normal','hello there','normal',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (3,9,'normal','hello there','normal',NULL);
INSERT INTO MESSAGES(sender_Id,rec_Id,message_subject,message_body,type,reply) VALUES (3,10,'normal','hello there','normal',NULL);

INSERT INTO VENUES(venue_name,city,state,about,snow_sports,water_sports,land_sports,air_sports) VALUES ('mountain1','some mountaint town','UT','some description','snowboard,ski,snowmobile',NULL,'mountainBiking',NULL);
INSERT INTO VENUES(venue_name,city,state,about,snow_sports,water_sports,land_sports,air_sports) VALUES ('mountain2','some mountaint town','NY','something witty','snowboard,ski,snowmobile',NULL,NULL,'hangGlide');
INSERT INTO VENUES(venue_name,city,state,about,snow_sports,water_sports,land_sports,air_sports) VALUES ('mountain3','some mountaint town','CA','some description','snowboard,ski,snowmobile',NULL,NULL,'hangGlide');
INSERT INTO VENUES(venue_name,city,state,about,snow_sports,water_sports,land_sports,air_sports) VALUES ('mountain4','some mountaint town','CO','something witty','snowboard,ski',NULL,NULL,NULL);
INSERT INTO VENUES(venue_name,city,state,about,snow_sports,water_sports,land_sports,air_sports) VALUES ('mountain5','some mountaint town','UT','some description','snowboard,ski',NULL,'mountainBiking',NULL);
INSERT INTO VENUES(venue_name,city,state,about,snow_sports,water_sports,land_sports,air_sports) VALUES ('mountain6','some mountaint town','MT','something witty','snowboard,ski',NULL,NULL,NULL);
INSERT INTO VENUES(venue_name,city,state,about,snow_sports,water_sports,land_sports,air_sports) VALUES ('mountain7','some mountaint town','NH','some description','snowboard,ski,snowmobile',NULL,NULL,'hangGlide');
INSERT INTO VENUES(venue_name,city,state,about,snow_sports,water_sports,land_sports,air_sports) VALUES ('mountain8','some mountaint town','VT','something witty','snowboard,ski,snowmobile',NULL,NULL,NULL);
INSERT INTO VENUES(venue_name,city,state,about,snow_sports,water_sports,land_sports,air_sports) VALUES ('mountain9','some mountaint town','AK','some description','snowboard,ski,snowmobile',NULL,'mountainBiking',NULL);
INSERT INTO VENUES(venue_name,city,state,about,snow_sports,water_sports,land_sports,air_sports) VALUES ('mountain10','some mountaint town','VT','something witty',NULL,NULL,NULL,NULL);
INSERT INTO VENUES(venue_name,city,state,about,snow_sports,water_sports,land_sports,air_sports) VALUES ('beach1','some ocean town','NJ','some description',NULL,'surf',NULL,NULL);
INSERT INTO VENUES(venue_name,city,state,about,snow_sports,water_sports,land_sports,air_sports) VALUES ('beach2','some ocean town','CA','something witty',NULL,'surf',NULL,NULL);
INSERT INTO VENUES(venue_name,city,state,about,snow_sports,water_sports,land_sports,air_sports) VALUES ('beach3','some ocean town','HI','some description',NULL,'surf',NULL,NULL);
INSERT INTO VENUES(venue_name,city,state,about,snow_sports,water_sports,land_sports,air_sports) VALUES ('beach4','some ocean town','NC','something witty',NULL,'surf,waterski',NULL,NULL);
INSERT INTO VENUES(venue_name,city,state,about,snow_sports,water_sports,land_sports,air_sports) VALUES ('beach5','some ocean town','FL','some description',NULL,'surf,waterski',NULL,NULL);
INSERT INTO VENUES(venue_name,city,state,about,snow_sports,water_sports,land_sports,air_sports) VALUES ('lake1','some lake town','MT','something witty','snowmobile','waterski',NULL,NULL);
INSERT INTO VENUES(venue_name,city,state,about,snow_sports,water_sports,land_sports,air_sports) VALUES ('lake2','some lake town','NY','some description',NULL,'waterski',NULL,NULL);
INSERT INTO VENUES(venue_name,city,state,about,snow_sports,water_sports,land_sports,air_sports) VALUES ('skatepark1','some skatepark town','NJ','something witty',NULL,NULL,'skateboard',NULL);
INSERT INTO VENUES(venue_name,city,state,about,snow_sports,water_sports,land_sports,air_sports) VALUES ('skatepark2','some skatepark town','NY','some description',NULL,NULL,'skateboard',NULL);
INSERT INTO VENUES(venue_name,city,state,about,snow_sports,water_sports,land_sports,air_sports) VALUES ('skatepark3','some skatepark town','PA','something witty',NULL,NULL,'skateboard',NULL);
INSERT INTO VENUES(venue_name,city,state,about,snow_sports,water_sports,land_sports,air_sports) VALUES ('skatepark4','some skatepark town','CA','some description',NULL,NULL,'skateboard',NULL);
INSERT INTO VENUES(venue_name,city,state,about,snow_sports,water_sports,land_sports,air_sports) VALUES ('skatepark5','some skatepark town','WA','something witty',NULL,NULL,'skateboard',NULL);
INSERT INTO VENUES(venue_name,city,state,about,snow_sports,water_sports,land_sports,air_sports) VALUES ('bmxcourse1','some bmxcourse town','NJ','some description',NULL,NULL,'BMX',NULL);
INSERT INTO VENUES(venue_name,city,state,about,snow_sports,water_sports,land_sports,air_sports) VALUES ('bmxcourse2','some bmxcourse town','NY','something witty',NULL,NULL,'BMX',NULL);
INSERT INTO VENUES(venue_name,city,state,about,snow_sports,water_sports,land_sports,air_sports) VALUES ('bmxcourse3','some bmxcourse town','PA','some description',NULL,NULL,'BMX',NULL);
INSERT INTO VENUES(venue_name,city,state,about,snow_sports,water_sports,land_sports,air_sports) VALUES ('bmxcourse4','some bmxcourse town','CA','something witty',NULL,NULL,'BMX',NULL);
INSERT INTO VENUES(venue_name,city,state,about,snow_sports,water_sports,land_sports,air_sports) VALUES ('bmxcourse5','some bmxcourse town','WA','some description',NULL,NULL,'BMX',NULL);
INSERT INTO VENUES(venue_name,city,state,about,snow_sports,water_sports,land_sports,air_sports) VALUES ('airfield1','some airfield town','NJ','something witty','snowmobile',NULL,NULL,'skydive');
INSERT INTO VENUES(venue_name,city,state,about,snow_sports,water_sports,land_sports,air_sports) VALUES ('airfield2','some airfield town','NY','some description',NULL,NULL,NULL,'skydive');
INSERT INTO VENUES(venue_name,city,state,about,snow_sports,water_sports,land_sports,air_sports) VALUES ('airfield3','some airfield town','PA','something witty',NULL,NULL,NULL,'skydive');
INSERT INTO VENUES(venue_name,city,state,about,snow_sports,water_sports,land_sports,air_sports) VALUES ('airfield4','some airfield town','CA','some description',NULL,NULL,NULL,'skydive');
INSERT INTO VENUES(venue_name,city,state,about,snow_sports,water_sports,land_sports,air_sports) VALUES ('airfield5','some airfield town','WA','something witty',NULL,NULL,NULL,'skydive');

INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (1,NULL,NULL);
INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (1,2,'buddy');
INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (1,3,'buddy');
INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (1,4,'follow');
INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (1,5,'follow');
INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (1,6,'block');
INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (1,7,'block');
INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (1,8,'buddy');
INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (1,9,'buddy');
INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (1,10,'buddy');
INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (1,11,'follow');
INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (1,12,'follow');
INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (1,13,'block');
INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (1,14,'block');
INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (1,15,'buddy');
INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (2,22,'buddy');
INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (2,3,'buddy');
INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (2,4,'follow');
INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (2,5,'follow');
INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (2,6,'block');
INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (2,7,'block');
INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (2,8,'buddy');
INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (2,9,'buddy');
INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (2,10,'buddy');
INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (2,11,'follow');
INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (2,12,'follow');
INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (2,13,'block');
INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (2,14,'block');
INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (2,15,'buddy');
INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (3,22,'buddy');
INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (3,3,'buddy');
INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (3,4,'follow');
INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (3,5,'follow');
INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (3,6,'block');
INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (3,7,'block');
INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (3,8,'buddy');
INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (3,9,'buddy');
INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (3,10,'buddy');
INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (3,11,'follow');
INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (3,12,'follow');
INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (3,13,'block');
INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (3,14,'block');
INSERT INTO FOLLOWS(user_id1,user_id2,type) VALUES (3,15,'buddy');


INSERT INTO FOLLOWS(user_id1,venue_id,type) VALUES (1,1,'follow');
INSERT INTO FOLLOWS(user_id1,venue_id,type) VALUES (1,2,'follow');
INSERT INTO FOLLOWS(user_id1,venue_id,type) VALUES (1,3,'follow');
INSERT INTO FOLLOWS(user_id1,venue_id,type) VALUES (1,4,'follow');
INSERT INTO FOLLOWS(user_id1,venue_id,type) VALUES (1,5,'follow');
INSERT INTO FOLLOWS(user_id1,venue_id,type) VALUES (1,6,'follow');
INSERT INTO FOLLOWS(user_id1,venue_id,type) VALUES (1,7,'follow');
INSERT INTO FOLLOWS(user_id1,venue_id,type) VALUES (1,8,'follow');
INSERT INTO FOLLOWS(user_id1,venue_id,type) VALUES (1,9,'follow');
INSERT INTO FOLLOWS(user_id1,venue_id,type) VALUES (1,10,'follow');
INSERT INTO FOLLOWS(user_id1,venue_id,type) VALUES (2,1,'follow');
INSERT INTO FOLLOWS(user_id1,venue_id,type) VALUES (2,2,'follow');
INSERT INTO FOLLOWS(user_id1,venue_id,type) VALUES (2,3,'follow');
INSERT INTO FOLLOWS(user_id1,venue_id,type) VALUES (2,4,'follow');
INSERT INTO FOLLOWS(user_id1,venue_id,type) VALUES (2,5,'follow');
INSERT INTO FOLLOWS(user_id1,venue_id,type) VALUES (2,6,'follow');
INSERT INTO FOLLOWS(user_id1,venue_id,type) VALUES (2,7,'follow');
INSERT INTO FOLLOWS(user_id1,venue_id,type) VALUES (2,8,'follow');
INSERT INTO FOLLOWS(user_id1,venue_id,type) VALUES (2,9,'follow');
INSERT INTO FOLLOWS(user_id1,venue_id,type) VALUES (2,10,'follow');
INSERT INTO FOLLOWS(user_id1,venue_id,type) VALUES (3,1,'follow');
INSERT INTO FOLLOWS(user_id1,venue_id,type) VALUES (3,2,'follow');
INSERT INTO FOLLOWS(user_id1,venue_id,type) VALUES (3,3,'follow');
INSERT INTO FOLLOWS(user_id1,venue_id,type) VALUES (3,4,'follow');
INSERT INTO FOLLOWS(user_id1,venue_id,type) VALUES (3,5,'follow');
INSERT INTO FOLLOWS(user_id1,venue_id,type) VALUES (3,6,'follow');
INSERT INTO FOLLOWS(user_id1,venue_id,type) VALUES (3,7,'follow');
INSERT INTO FOLLOWS(user_id1,venue_id,type) VALUES (3,8,'follow');
INSERT INTO FOLLOWS(user_id1,venue_id,type) VALUES (3,9,'follow');
INSERT INTO FOLLOWS(user_id1,venue_id,type) VALUES (3,10,'follow');

INSERT INTO CARVES(name,creator,venue,type,max_athletes,max_photo,date,completed,sports,description) VALUES ('carve1',1,1,'open',5,1,'2019-03-24',0,'snowboard,ski',"I am Venue!");
INSERT INTO CARVES(name,creator,venue,type,max_athletes,max_photo,date,completed,sports,description) VALUES ('carve2',1,11,'buddy',10,2,'2019-03-25',0,'surf',"I am Venue!");
INSERT INTO CARVES(name,creator,venue,type,max_athletes,max_photo,date,completed,sports,description) VALUES ('carve3',1,18,'open',5,1,'2019-03-26',0,'skateboard',"I am Venue!");
INSERT INTO CARVES(name,creator,venue,type,max_athletes,max_photo,date,completed,sports,description) VALUES ('carve4',1,24,'open',10,2,'2019-03-27',0,'BMX',"I am Venue!");
INSERT INTO CARVES(name,creator,venue,type,max_athletes,max_photo,date,completed,sports,description) VALUES ('carve5',1,3,'open',5,1,'2019-03-28',0,'hangGlide',"I am Venue!");
INSERT INTO CARVES(name,creator,venue,type,max_athletes,max_photo,date,completed,sports,description) VALUES ('carve6',2,2,'buddy',10,2,'2019-03-29',0,'snowmobile',"I am Venue!");
INSERT INTO CARVES(name,creator,venue,type,max_athletes,max_photo,date,completed,sports,description) VALUES ('carve7',2,12,'buddy',10,1,'2019-03-30',0,'surf',"I am Venue!");
INSERT INTO CARVES(name,creator,venue,type,max_athletes,max_photo,date,completed,sports,description) VALUES ('carve8',2,16,'open',10,2,'2019-03-31',0,'waterSki',"I am Venue!");
INSERT INTO CARVES(name,creator,venue,type,max_athletes,max_photo,date,completed,sports,description) VALUES ('carve9',2,1,'open',10,1,'2019-04-01',0,'snowboard,ski',"I am Venue!");
INSERT INTO CARVES(name,creator,venue,type,max_athletes,max_photo,date,completed,sports,description) VALUES ('carve10',2,11,'open',10,2,'2019-04-02',0,'surf',"I am Venue!");
INSERT INTO CARVES(name,creator,venue,type,max_athletes,max_photo,date,completed,sports,description) VALUES ('carve11',3,18,'open',10,1,'2019-04-03',0,'skateboard',"I am Venue!");
INSERT INTO CARVES(name,creator,venue,type,max_athletes,max_photo,date,completed,sports,description) VALUES ('carve12',4,24,'open',10,2,'2019-04-04',0,'BMX',"I am Venue!");
INSERT INTO CARVES(name,creator,venue,type,max_athletes,max_photo,date,completed,sports,description) VALUES ('carve13',5,3,'open',10,1,'2019-04-05',0,'hangGlide',"I am Venue!");
INSERT INTO CARVES(name,creator,venue,type,max_athletes,max_photo,date,completed,sports,description) VALUES ('carve14',6,2,'buddy',10,2,'2019-04-06',0,'snowmobile',"I am Venue!");
INSERT INTO CARVES(name,creator,venue,type,max_athletes,max_photo,date,completed,sports,description) VALUES ('carve15',7,12,'open',10,3,'2019-04-07',0,'surf',"I am Venue!");
INSERT INTO CARVES(name,creator,venue,type,max_athletes,max_photo,date,completed,sports,description) VALUES ('carve16',8,16,'open',10,1,'2019-03-01',1,'waterSki',"I am Venue!");
INSERT INTO CARVES(name,creator,venue,type,max_athletes,max_photo,date,completed,sports,description) VALUES ('carve17',2,1,'open',10,2,'2019-03-02',1,'snowboard,ski',"I am Venue!");
INSERT INTO CARVES(name,creator,venue,type,max_athletes,max_photo,date,completed,sports,description) VALUES ('carve18',3,11,'open',10,3,'2019-03-03',1,'surf',"I am Venue!");
INSERT INTO CARVES(name,creator,venue,type,max_athletes,max_photo,date,completed,sports,description) VALUES ('carve19',4,18,'open',10,1,'2019-03-04',1,'skateboard',"I am Venue!");
INSERT INTO CARVES(name,creator,venue,type,max_athletes,max_photo,date,completed,sports,description) VALUES ('carve20',5,24,'open',10,2,'2019-03-05',1,'BMX',"I am Venue!");
INSERT INTO CARVES(name,creator,venue,type,max_athletes,max_photo,date,completed,sports,description) VALUES ('carve21',6,3,'open',10,3,'2019-03-06',1,'hangGlide',"I am Venue!");
INSERT INTO CARVES(name,creator,venue,type,max_athletes,max_photo,date,completed,sports,description) VALUES ('carve22',7,2,'buddy',10,1,'2019-03-07',1,'snowmobile',"I am Venue!");
INSERT INTO CARVES(name,creator,venue,type,max_athletes,max_photo,date,completed,sports,description) VALUES ('carve23',9,12,'open',10,2,'2019-03-08',1,'surf',"I am Venue!");
INSERT INTO CARVES(name,creator,venue,type,max_athletes,max_photo,date,completed,sports,description) VALUES ('carve24',10,16,'open',10,3,'2019-03-09',1,'waterSki',"I am Venue!");
INSERT INTO CARVES(name,creator,venue,type,max_athletes,max_photo,date,completed,sports,description) VALUES ('carve25',11,1,'open',10,1,'2019-03-10',1,'snowboard,ski',"I am Venue!");
INSERT INTO CARVES(name,creator,venue,type,max_athletes,max_photo,date,completed,sports,description) VALUES ('carve26',12,11,'open',10,2,'2019-03-11',1,'surf',"I am Venue!");
INSERT INTO CARVES(name,creator,venue,type,max_athletes,max_photo,date,completed,sports,description) VALUES ('carve27',1,18,'open',10,3,'2019-03-12',1,'skateboard',"I am Venue!");
INSERT INTO CARVES(name,creator,venue,type,max_athletes,max_photo,date,completed,sports,description) VALUES ('carve28',1,24,'open',10,1,'2019-03-13',1,'BMX',"I am Venue!");
INSERT INTO CARVES(name,creator,venue,type,max_athletes,max_photo,date,completed,sports,description) VALUES ('carve29',1,3,'open',10,2,'2019-03-14',1,'hangGlide',"I am Venue!");
INSERT INTO CARVES(name,creator,venue,type,max_athletes,max_photo,date,completed,sports,description) VALUES ('carve30',1,2,'open',10,3,'2019-03-15',1,'snowmobile',"I am Venue!");



INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (1,2,'photographer');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (1,3,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (1,4,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (1,5,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (1,6,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (2,2,'photographer');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (2,3,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (2,4,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (2,5,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (2,6,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (3,2,'photographer');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (3,3,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (3,4,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (3,5,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (3,6,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (4,2,'photographer');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (4,3,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (4,4,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (4,5,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (4,6,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (5,2,'photographer');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (5,3,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (5,4,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (5,5,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (5,6,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (6,2,'photographer');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (6,3,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (6,4,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (6,5,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (6,6,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (7,2,'photographer');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (7,3,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (7,4,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (7,5,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (7,6,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (8,2,'photographer');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (8,3,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (8,4,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (8,5,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (8,6,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (9,2,'photographer');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (9,3,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (9,4,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (9,5,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (9,6,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (10,2,'photographer');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (10,3,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (10,4,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (10,5,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (10,6,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (6,1,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (7,1,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (8,1,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (9,1,'athlete');
INSERT INTO CARVE_ATTENDEES(carve,user,type) VALUES (10,1,'athlete');

INSERT INTO MEDIA(poster,url,description,carve) VALUES (1,'https://www.youtube.com/embed/7a0hbT0QtSw','cool video',1);
INSERT INTO MEDIA(poster,url,description,carve) VALUES (1,'www.youtube.com','cool video',2);
INSERT INTO MEDIA(poster,url,description,carve) VALUES (1,'www.youtube.com','cool video',3);
INSERT INTO MEDIA(poster,url,description,carve) VALUES (8,'https://www.youtube.com/watch?v=WvGopsM1G9g','filler video',15);
INSERT INTO MEDIA(poster,url,description,carve) VALUES (2,'https://www.youtube.com/watch?v=tHHxTHZwFUw','filler video',16);
INSERT INTO MEDIA(poster,url,description,carve) VALUES (3,'https://www.youtube.com/watch?v=NQZJ0zbouIg','filler video',17);
INSERT INTO MEDIA(poster,url,description,carve) VALUES (4,'https://www.youtube.com/watch?v=RRZ39KS6Vpk','filler video',18);
INSERT INTO MEDIA(poster,url,description,carve) VALUES (5,'https://www.youtube.com/watch?v=YThX7_8I3m0','filler video',19);
INSERT INTO MEDIA(poster,url,description,carve) VALUES (6,'https://www.youtube.com/watch?v=pBUGyN6d1xU','filler video',20);
INSERT INTO MEDIA(poster,url,description,carve) VALUES (7,'https://www.youtube.com/watch?v=trzTOlZtUYc','filler video',21);
INSERT INTO MEDIA(poster,url,description,carve) VALUES (9,'https://www.youtube.com/watch?v=NQZJ0zbouIg','filler video',22);
INSERT INTO MEDIA(poster,url,description,carve) VALUES (10,'https://www.youtube.com/watch?v=WvGopsM1G9g','filler video',23);
INSERT INTO MEDIA(poster,url,description,carve) VALUES (11,'https://www.youtube.com/watch?v=tHHxTHZwFUw','filler video',24);
INSERT INTO MEDIA(poster,url,description,carve) VALUES (12,'https://www.youtube.com/watch?v=NQZJ0zbouIg','filler video',25);
INSERT INTO MEDIA(poster,url,description,carve) VALUES (1,'https://www.youtube.com/watch?v=ul8h5xTtSzE','filler video',26);
INSERT INTO MEDIA(poster,url,description,carve) VALUES (1,'https://www.youtube.com/watch?v=YThX7_8I3m0','filler video',27);
INSERT INTO MEDIA(poster,url,description,carve) VALUES (1,'https://www.youtube.com/watch?v=pBUGyN6d1xU','filler video',28);
INSERT INTO MEDIA(poster,url,description,carve) VALUES (1,'https://www.youtube.com/watch?v=trzTOlZtUYc','filler video',29);
INSERT INTO MEDIA(poster,url,description,carve) VALUES (3,'https://www.youtube.com/watch?v=tHHxTHZwFUw','filler video',4);
INSERT INTO MEDIA(poster,url,description,carve) VALUES (23,'https://www.youtube.com/watch?v=YThX7_8I3m0','filler video',5);
INSERT INTO MEDIA(poster,url,description,carve) VALUES (7,'https://www.youtube.com/watch?v=tHHxTHZwFUw','filler video',6);
INSERT INTO MEDIA(poster,url,description,carve) VALUES (34,'https://www.youtube.com/watch?v=RRZ39KS6Vpk','filler video',7);
INSERT INTO MEDIA(poster,url,description,carve) VALUES (35,'https://www.youtube.com/watch?v=RRZ39KS6Vpk','filler video',8);
INSERT INTO MEDIA(poster,url,description,carve) VALUES (40,'https://www.youtube.com/watch?v=trzTOlZtUYc','filler video',2);
INSERT INTO MEDIA(poster,url,description,venue) VALUES (1,'www.youtube.com','cool video',2);
INSERT INTO MEDIA(poster,url,description,venue) VALUES (1,'www.youtube.com','cool video',1);
INSERT INTO MEDIA(poster,url,description,venue) VALUES (1,'www.youtube.com','cool video',4);
INSERT INTO MEDIA(poster,url,description,venue) VALUES (8,'https://www.youtube.com/watch?v=WvGopsM1G9g','filler video',16);
INSERT INTO MEDIA(poster,url,description,venue) VALUES (2,'https://www.youtube.com/watch?v=tHHxTHZwFUw','filler video',1);
INSERT INTO MEDIA(poster,url,description,venue) VALUES (3,'https://www.youtube.com/watch?v=NQZJ0zbouIg','filler video',11);
INSERT INTO MEDIA(poster,url,description,venue) VALUES (4,'https://www.youtube.com/watch?v=RRZ39KS6Vpk','filler video',18);
INSERT INTO MEDIA(poster,url,description,venue) VALUES (5,'https://www.youtube.com/watch?v=YThX7_8I3m0','filler video',24);
INSERT INTO MEDIA(poster,url,description,venue) VALUES (6,'https://www.youtube.com/watch?v=pBUGyN6d1xU','filler video',3);
INSERT INTO MEDIA(poster,url,description,venue) VALUES (7,'https://www.youtube.com/watch?v=trzTOlZtUYc','filler video',9);
INSERT INTO MEDIA(poster,url,description,venue) VALUES (9,'https://www.youtube.com/watch?v=NQZJ0zbouIg','filler video',12);
INSERT INTO MEDIA(poster,url,description,venue) VALUES (10,'https://www.youtube.com/watch?v=WvGopsM1G9g','filler video',16);
INSERT INTO MEDIA(poster,url,description,venue) VALUES (11,'https://www.youtube.com/watch?v=tHHxTHZwFUw','filler video',1);
INSERT INTO MEDIA(poster,url,description,venue) VALUES (12,'https://www.youtube.com/watch?v=NQZJ0zbouIg','filler video',12);
INSERT INTO MEDIA(poster,url,description,venue) VALUES (1,'https://www.youtube.com/watch?v=ul8h5xTtSzE','filler video',18);
INSERT INTO MEDIA(poster,url,description,venue) VALUES (1,'https://www.youtube.com/watch?v=YThX7_8I3m0','filler video',24);
INSERT INTO MEDIA(poster,url,description,venue) VALUES (1,'https://www.youtube.com/watch?v=pBUGyN6d1xU','filler video',3);
INSERT INTO MEDIA(poster,url,description,venue) VALUES (1,'https://www.youtube.com/watch?v=trzTOlZtUYc','filler video',2);
INSERT INTO MEDIA(poster,url,description,venue) VALUES (3,'https://www.youtube.com/watch?v=tHHxTHZwFUw','filler video',25);
INSERT INTO MEDIA(poster,url,description,venue) VALUES (23,'https://www.youtube.com/watch?v=YThX7_8I3m0','filler video',26);
INSERT INTO MEDIA(poster,url,description,venue) VALUES (7,'https://www.youtube.com/watch?v=tHHxTHZwFUw','filler video',27);
INSERT INTO MEDIA(poster,url,description,venue) VALUES (34,'https://www.youtube.com/watch?v=RRZ39KS6Vpk','filler video',28);
INSERT INTO MEDIA(poster,url,description,venue) VALUES (35,'https://www.youtube.com/watch?v=RRZ39KS6Vpk','filler video',29);
INSERT INTO MEDIA(poster,url,description,venue) VALUES (40,'https://www.youtube.com/watch?v=trzTOlZtUYc','filler video',2);
INSERT INTO MEDIA(poster,url,description,profile) VALUES (1,'www.youtube.com','cool video',NULL);
INSERT INTO MEDIA(poster,url,description,profile) VALUES (1,'www.youtube.com','cool video',NULL);
INSERT INTO MEDIA(poster,url,description,profile) VALUES (1,'www.youtube.com','cool video',1);
INSERT INTO MEDIA(poster,url,description,profile) VALUES (8,'https://www.youtube.com/watch?v=WvGopsM1G9g','filler video',8);
INSERT INTO MEDIA(poster,url,description,profile) VALUES (2,'https://www.youtube.com/watch?v=tHHxTHZwFUw','filler video',2);
INSERT INTO MEDIA(poster,url,description,profile) VALUES (3,'https://www.youtube.com/watch?v=NQZJ0zbouIg','filler video',3);
INSERT INTO MEDIA(poster,url,description,profile) VALUES (4,'https://www.youtube.com/watch?v=RRZ39KS6Vpk','filler video',4);
INSERT INTO MEDIA(poster,url,description,profile) VALUES (5,'https://www.youtube.com/watch?v=YThX7_8I3m0','filler video',5);
INSERT INTO MEDIA(poster,url,description,profile) VALUES (6,'https://www.youtube.com/watch?v=pBUGyN6d1xU','filler video',6);
INSERT INTO MEDIA(poster,url,description,profile) VALUES (7,'https://www.youtube.com/watch?v=trzTOlZtUYc','filler video',7);
INSERT INTO MEDIA(poster,url,description,profile) VALUES (9,'https://www.youtube.com/watch?v=NQZJ0zbouIg','filler video',9);
INSERT INTO MEDIA(poster,url,description,profile) VALUES (10,'https://www.youtube.com/watch?v=WvGopsM1G9g','filler video',10);
INSERT INTO MEDIA(poster,url,description,profile) VALUES (11,'https://www.youtube.com/watch?v=tHHxTHZwFUw','filler video',11);
INSERT INTO MEDIA(poster,url,description,profile) VALUES (12,'https://www.youtube.com/watch?v=NQZJ0zbouIg','filler video',12);
INSERT INTO MEDIA(poster,url,description,profile) VALUES (1,'https://www.youtube.com/watch?v=ul8h5xTtSzE','filler video',1);
INSERT INTO MEDIA(poster,url,description,profile) VALUES (1,'https://www.youtube.com/watch?v=YThX7_8I3m0','filler video',1);
INSERT INTO MEDIA(poster,url,description,profile) VALUES (1,'https://www.youtube.com/watch?v=pBUGyN6d1xU','filler video',1);
INSERT INTO MEDIA(poster,url,description,profile) VALUES (1,'https://www.youtube.com/watch?v=trzTOlZtUYc','filler video',1);
INSERT INTO MEDIA(poster,url,description,profile) VALUES (3,'https://www.youtube.com/watch?v=tHHxTHZwFUw','filler video',3);
INSERT INTO MEDIA(poster,url,description,profile) VALUES (23,'https://www.youtube.com/watch?v=YThX7_8I3m0','filler video',23);
INSERT INTO MEDIA(poster,url,description,profile) VALUES (7,'https://www.youtube.com/watch?v=tHHxTHZwFUw','filler video',7);
INSERT INTO MEDIA(poster,url,description,profile) VALUES (34,'https://www.youtube.com/watch?v=RRZ39KS6Vpk','filler video',34);
INSERT INTO MEDIA(poster,url,description,profile) VALUES (35,'https://www.youtube.com/watch?v=RRZ39KS6Vpk','filler video',35);
INSERT INTO MEDIA(poster,url,description,profile) VALUES (40,'https://www.youtube.com/watch?v=trzTOlZtUYc','filler video',40);

INSERT INTO COMMENTS(poster,carve,comment) VALUES (1,1,'carve comment something witty goes here');
INSERT INTO COMMENTS(poster,carve,comment) VALUES (1,2,'carve comment something witty goes here');
INSERT INTO COMMENTS(poster,carve,comment) VALUES (1,3,'carve comment something witty goes here');
INSERT INTO COMMENTS(poster,carve,comment) VALUES (1,4,'carve comment something witty goes here');
INSERT INTO COMMENTS(poster,carve,comment) VALUES (1,5,'carve comment something witty goes here');
INSERT INTO COMMENTS(poster,carve,comment) VALUES (1,6,'carve comment something witty goes here');
INSERT INTO COMMENTS(poster,carve,comment) VALUES (2,7,'carve comment something witty goes here');
INSERT INTO COMMENTS(poster,carve,comment) VALUES (3,8,'carve comment something witty goes here');
INSERT INTO COMMENTS(poster,carve,comment) VALUES (4,1,'carve comment something witty goes here');
INSERT INTO COMMENTS(poster,carve,comment) VALUES (5,2,'carve comment something witty goes here');
INSERT INTO COMMENTS(poster,carve,comment) VALUES (1,3,'carve comment something witty goes here');
INSERT INTO COMMENTS(poster,carve,comment) VALUES (2,4,'carve comment something witty goes here');
INSERT INTO COMMENTS(poster,carve,comment) VALUES (3,5,'carve comment something witty goes here');
INSERT INTO COMMENTS(poster,carve,comment) VALUES (4,6,'carve comment something witty goes here');
INSERT INTO COMMENTS(poster,carve,comment) VALUES (5,7,'carve comment something witty goes here');
INSERT INTO COMMENTS(poster,carve,comment) VALUES (1,8,'carve comment something witty goes here');
INSERT INTO COMMENTS(poster,carve,comment) VALUES (2,9,'carve comment something witty goes here');
INSERT INTO COMMENTS(poster,carve,comment) VALUES (3,1,'carve comment something witty goes here');
INSERT INTO COMMENTS(poster,carve,comment) VALUES (4,2,'carve comment something witty goes here');
INSERT INTO COMMENTS(poster,carve,comment) VALUES (5,3,'carve comment something witty goes here');
INSERT INTO COMMENTS(poster,MEDIA,comment) VALUES (1,1,'medai comment about the video/ phot cool or something');
INSERT INTO COMMENTS(poster,MEDIA,comment) VALUES (1,2,'medai comment about the video/ phot cool or something');
INSERT INTO COMMENTS(poster,MEDIA,comment) VALUES (1,3,'medai comment about the video/ phot cool or something');
INSERT INTO COMMENTS(poster,MEDIA,comment) VALUES (1,4,'medai comment about the video/ phot cool or something');
INSERT INTO COMMENTS(poster,MEDIA,comment) VALUES (1,5,'medai comment about the video/ phot cool or something');
INSERT INTO COMMENTS(poster,MEDIA,comment) VALUES (1,6,'medai comment about the video/ phot cool or something');
INSERT INTO COMMENTS(poster,MEDIA,comment) VALUES (2,7,'medai comment about the video/ phot cool or something');
INSERT INTO COMMENTS(poster,MEDIA,comment) VALUES (3,8,'medai comment about the video/ phot cool or something');
INSERT INTO COMMENTS(poster,MEDIA,comment) VALUES (4,1,'medai comment about the video/ phot cool or something');
INSERT INTO COMMENTS(poster,MEDIA,comment) VALUES (5,2,'medai comment about the video/ phot cool or something');
INSERT INTO COMMENTS(poster,MEDIA,comment) VALUES (1,3,'medai comment about the video/ phot cool or something');
INSERT INTO COMMENTS(poster,MEDIA,comment) VALUES (2,4,'medai comment about the video/ phot cool or something');
INSERT INTO COMMENTS(poster,MEDIA,comment) VALUES (3,5,'medai comment about the video/ phot cool or something');
INSERT INTO COMMENTS(poster,MEDIA,comment) VALUES (4,6,'medai comment about the video/ phot cool or something');
INSERT INTO COMMENTS(poster,MEDIA,comment) VALUES (5,7,'medai comment about the video/ phot cool or something');
INSERT INTO COMMENTS(poster,MEDIA,comment) VALUES (1,8,'medai comment about the video/ phot cool or something');
INSERT INTO COMMENTS(poster,MEDIA,comment) VALUES (2,9,'medai comment about the video/ phot cool or something');
INSERT INTO COMMENTS(poster,MEDIA,comment) VALUES (3,1,'medai comment about the video/ phot cool or something');
INSERT INTO COMMENTS(poster,MEDIA,comment) VALUES (4,2,'medai comment about the video/ phot cool or something');
INSERT INTO COMMENTS(poster,MEDIA,comment) VALUES (5,3,'medai comment about the video/ phot cool or something');
INSERT INTO COMMENTS(poster,profile,comment) VALUES (1,1,'profile wall post equivalent something goes here');
INSERT INTO COMMENTS(poster,profile,comment) VALUES (1,2,'profile wall post equivalent something goes here');
INSERT INTO COMMENTS(poster,profile,comment) VALUES (1,3,'profile wall post equivalent something goes here');
INSERT INTO COMMENTS(poster,profile,comment) VALUES (1,4,'profile wall post equivalent something goes here');
INSERT INTO COMMENTS(poster,profile,comment) VALUES (1,5,'profile wall post equivalent something goes here');
INSERT INTO COMMENTS(poster,profile,comment) VALUES (1,6,'profile wall post equivalent something goes here');
INSERT INTO COMMENTS(poster,profile,comment) VALUES (2,7,'profile wall post equivalent something goes here');
INSERT INTO COMMENTS(poster,profile,comment) VALUES (3,8,'profile wall post equivalent something goes here');
INSERT INTO COMMENTS(poster,profile,comment) VALUES (4,1,'profile wall post equivalent something goes here');
INSERT INTO COMMENTS(poster,profile,comment) VALUES (5,2,'profile wall post equivalent something goes here');
INSERT INTO COMMENTS(poster,profile,comment) VALUES (1,3,'profile wall post equivalent something goes here');
INSERT INTO COMMENTS(poster,profile,comment) VALUES (2,4,'profile wall post equivalent something goes here');
INSERT INTO COMMENTS(poster,profile,comment) VALUES (3,5,'profile wall post equivalent something goes here');
INSERT INTO COMMENTS(poster,profile,comment) VALUES (4,6,'profile wall post equivalent something goes here');
INSERT INTO COMMENTS(poster,profile,comment) VALUES (5,7,'profile wall post equivalent something goes here');
INSERT INTO COMMENTS(poster,profile,comment) VALUES (1,8,'profile wall post equivalent something goes here');
INSERT INTO COMMENTS(poster,profile,comment) VALUES (2,9,'profile wall post equivalent something goes here');
INSERT INTO COMMENTS(poster,profile,comment) VALUES (3,1,'profile wall post equivalent something goes here');
INSERT INTO COMMENTS(poster,profile,comment) VALUES (4,2,'profile wall post equivalent something goes here');
INSERT INTO COMMENTS(poster,profile,comment) VALUES (5,3,'profile wall post equivalent something goes here');


INSERT INTO LIKES(poster,type,carve) VALUES (1,'like',1);
INSERT INTO LIKES(poster,type,carve) VALUES (1,'dislike',2);
INSERT INTO LIKES(poster,type,carve) VALUES (1,'like',3);
INSERT INTO LIKES(poster,type,carve) VALUES (1,'dislike',4);
INSERT INTO LIKES(poster,type,carve) VALUES (1,'like',5);
INSERT INTO LIKES(poster,type,carve) VALUES (1,'dislike',6);
INSERT INTO LIKES(poster,type,carve) VALUES (1,'like',7);
INSERT INTO LIKES(poster,type,carve) VALUES (1,'dislike',8);
INSERT INTO LIKES(poster,type,carve) VALUES (1,'like',9);
INSERT INTO LIKES(poster,type,carve) VALUES (1,'dislike',1);
INSERT INTO LIKES(poster,type,carve) VALUES (1,'like',2);
INSERT INTO LIKES(poster,type,carve) VALUES (2,'dislike',3);
INSERT INTO LIKES(poster,type,carve) VALUES (2,'like',4);
INSERT INTO LIKES(poster,type,carve) VALUES (2,'dislike',5);
INSERT INTO LIKES(poster,type,carve) VALUES (2,'like',6);
INSERT INTO LIKES(poster,type,carve) VALUES (2,'dislike',7);
INSERT INTO LIKES(poster,type,carve) VALUES (2,'like',8);
INSERT INTO LIKES(poster,type,carve) VALUES (2,'dislike',9);
INSERT INTO LIKES(poster,type,carve) VALUES (2,'like',1);
INSERT INTO LIKES(poster,type,carve) VALUES (2,'dislike',2);
INSERT INTO LIKES(poster,type,carve) VALUES (2,'like',3);
INSERT INTO LIKES(poster,type,carve) VALUES (2,'dislike',4);
INSERT INTO LIKES(poster,type,carve) VALUES (2,'like',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (1,'like',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (1,'dislike',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (1,'like',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (1,'dislike',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (1,'like',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (1,'dislike',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (1,'like',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (1,'dislike',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (1,'like',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (1,'dislike',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (1,'like',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (2,'dislike',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (2,'like',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (2,'dislike',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (2,'like',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (2,'dislike',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (2,'like',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (2,'dislike',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (2,'like',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (2,'dislike',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (2,'like',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (2,'dislike',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (2,'like',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (2,'like',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (1,'like',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (1,'dislike',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (1,'like',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (1,'dislike',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (1,'like',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (1,'dislike',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (1,'like',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (1,'dislike',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (1,'like',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (1,'dislike',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (1,'like',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (2,'dislike',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (2,'like',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (2,'dislike',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (2,'like',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (2,'dislike',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (2,'like',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (2,'dislike',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (2,'like',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (2,'dislike',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (2,'like',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (2,'dislike',NULL);
INSERT INTO LIKES(poster,type,carve) VALUES (2,'like',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (1,'like',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (1,'dislike',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (1,'like',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (1,'dislike',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (1,'like',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (1,'dislike',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (1,'like',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (1,'dislike',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (1,'like',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (1,'dislike',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (1,'like',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (2,'dislike',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (2,'like',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (2,'dislike',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (2,'like',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (2,'dislike',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (2,'like',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (2,'dislike',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (2,'like',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (2,'dislike',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (2,'like',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (2,'dislike',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (2,'like',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (1,'like',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (1,'dislike',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (1,'like',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (1,'dislike',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (1,'like',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (1,'dislike',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (1,'like',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (1,'dislike',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (1,'like',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (1,'dislike',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (1,'like',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (2,'dislike',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (2,'like',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (2,'dislike',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (2,'like',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (2,'dislike',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (2,'like',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (2,'dislike',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (2,'like',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (2,'dislike',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (2,'like',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (2,'dislike',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (2,'like',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (2,'like',NULL);
INSERT INTO LIKES(poster,type,comment) VALUES (1,'like',1);
INSERT INTO LIKES(poster,type,comment) VALUES (1,'dislike',2);
INSERT INTO LIKES(poster,type,comment) VALUES (1,'like',3);
INSERT INTO LIKES(poster,type,comment) VALUES (1,'dislike',4);
INSERT INTO LIKES(poster,type,comment) VALUES (1,'like',5);
INSERT INTO LIKES(poster,type,comment) VALUES (1,'dislike',6);
INSERT INTO LIKES(poster,type,comment) VALUES (1,'like',7);
INSERT INTO LIKES(poster,type,comment) VALUES (1,'dislike',8);
INSERT INTO LIKES(poster,type,comment) VALUES (1,'like',9);
INSERT INTO LIKES(poster,type,comment) VALUES (1,'dislike',1);
INSERT INTO LIKES(poster,type,comment) VALUES (1,'like',2);
INSERT INTO LIKES(poster,type,comment) VALUES (2,'dislike',3);
INSERT INTO LIKES(poster,type,comment) VALUES (2,'like',4);
INSERT INTO LIKES(poster,type,comment) VALUES (2,'dislike',5);
INSERT INTO LIKES(poster,type,comment) VALUES (2,'like',6);
INSERT INTO LIKES(poster,type,comment) VALUES (2,'dislike',7);
INSERT INTO LIKES(poster,type,comment) VALUES (2,'like',8);
INSERT INTO LIKES(poster,type,comment) VALUES (2,'dislike',9);
INSERT INTO LIKES(poster,type,comment) VALUES (2,'like',1);
INSERT INTO LIKES(poster,type,comment) VALUES (2,'dislike',2);
INSERT INTO LIKES(poster,type,comment) VALUES (2,'like',3);
INSERT INTO LIKES(poster,type,comment) VALUES (2,'dislike',4);
INSERT INTO LIKES(poster,type,comment) VALUES (2,'like',5);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (1,'like',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (1,'dislike',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (1,'like',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (1,'dislike',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (1,'like',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (1,'dislike',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (1,'like',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (1,'dislike',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (1,'like',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (1,'dislike',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (1,'like',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (2,'dislike',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (2,'like',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (2,'dislike',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (2,'like',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (2,'dislike',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (2,'like',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (2,'dislike',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (2,'like',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (2,'dislike',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (2,'like',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (2,'dislike',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (2,'like',5);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (1,'like',1);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (1,'dislike',2);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (1,'like',3);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (1,'dislike',4);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (1,'like',5);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (1,'dislike',6);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (1,'like',7);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (1,'dislike',8);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (1,'like',9);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (1,'dislike',1);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (1,'like',2);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (2,'dislike',3);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (2,'like',4);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (2,'dislike',5);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (2,'like',6);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (2,'dislike',7);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (2,'like',8);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (2,'dislike',9);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (2,'like',1);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (2,'dislike',2);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (2,'like',3);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (2,'dislike',4);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (2,'like',5);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (2,'like',5);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (1,'like',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (1,'dislike',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (1,'like',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (1,'dislike',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (1,'like',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (1,'dislike',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (1,'like',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (1,'dislike',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (1,'like',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (1,'dislike',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (1,'like',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (2,'dislike',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (2,'like',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (2,'dislike',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (2,'like',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (2,'dislike',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (2,'like',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (2,'dislike',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (2,'like',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (2,'dislike',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (2,'like',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (2,'dislike',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (2,'like',NULL);
INSERT INTO LIKES(poster,type,MEDIA) VALUES (2,'like',NULL);







